Add accounts app
behumb/tasks pull request #10
Opened 2021-03-17 11:24 UTC by behumb

2021-03-17 11:32 UTC, denisorehovsky requested changes
Try to use viewsets where it makes sense

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/tests.py
> +# Create your tests here.
This file should be removed

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    re_path(r'users/count/registered/$', views.UserRegisteredCount.as_view(), name='user_registered'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    re_path(r'users/count/$', views.UserCount.as_view(), name='user_count'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    path('groups/', views.GroupList.as_view(), name='group_list'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    path('users/current', views.CurrentUserDetail.as_view(), name='current_user'),
Endpoints should end with "/"

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    re_path(r'users/$', views.UserList.as_view(), name='user_list'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    path('groups/user-count', views.GroupUsersCount.as_view(), name='groups_user_count'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/urls.py
> +    path('users/groups', views.UserGroups.as_view(), name='users_groups'),
Why do you need this endpoint?

2021-03-17 11:32 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    def patch(self, request, id):
I don't think this endpoint will work if I try to update the user partially. What if I don't send an email in the request body?

2021-03-19 06:38 UTC, denisorehovsky requested changes
Use viewsets where it makes sense. You still have a lot of views that are not used anywhere. Why do you need them? If the code is not used, it should be removed.

Have you finished accounts logic? If so, then how can I register as a teacher? How can I register as a student?

Also, it's better to make a pull request as small as possible since it's easier to review. I would create another pull request for frontend code.

2021-03-22 10:06 UTC, denisorehovsky requested changes
I still don't see that you used viewsets.

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/frontend/src/components/SignUp.vue
> +          for (let key in err.response.data) {
Read about DRY (Don't Repeat Yourself)

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/frontend/src/components/SignUp.vue
> +  b-container(fluid="lg")
Don't use "pug". This technology is old. Use pure HTML instead.

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/frontend/src/components/Login.vue
> +        console.log(this.$store.state.authUser)
What's the point of console.logs? Your code shouldn't have console logs at all.

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/frontend/src/api/accounts.js
> +      return response.data
I would remove this part:
```
.then(response => {
      return response.data
    })
```

Or use request interceptors. Remember DRY principle

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    def patch(self, request, id):
I still don't think that this endpoint will work if I only try to update an email, for example, without sending other information? Did you test this endpoint?

2021-03-22 10:06 UTC, denisorehovsky commented on training_service/frontend/src/components/SignUp.vue
> +        {value: 1, text: 'Teacher'},
You shouldn't hardcode IDs like that. You should get a list of groups from the backend. What if the IDs are 2 and 3? Your code will break.

2021-03-24 07:05 UTC, denisorehovsky requested changes

2021-03-24 07:05 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +class UserGroupFilter(django_filters.FilterSet):
This class should be moved to `filters.py` file

2021-03-24 07:05 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +class UserViewSet(mixins.RetrieveModelMixin,
Why do you need to inherit from mixins if you don't use them?

2021-03-24 07:05 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +class CurrentUserDetail(APIView):
I would remove this class and added `def current` action to `UserViewSet`

2021-03-24 07:05 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +# class ObtainToken(APIView):
Comments can be removed

2021-03-24 11:56 UTC, denisorehovsky requested changes

2021-03-24 11:56 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +class UserViewSet(mixins.CreateModelMixin,
Again, why do you need to inherit from mixins if you don't use them?

2021-03-24 11:56 UTC, denisorehovsky commented on training_service/backend/courses/enumerations.py
> +ROLES = (
Please, read this article https://adamj.eu/tech/2020/01/27/moving-to-django-3-field-choices-enumeration-types/

2021-03-24 11:56 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +
Models in this file have a lot of issues. Take a look at them again. Maybe you will find something.

Here are some hints:
- Read about many to many field in Django https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ManyToManyField
- How can I get a list of all course steps (reading material, test) ordered by their position numbers?
- What do I need to write in order to get the number of courses that were completed in 2021? You can write ORM query in the comments.

2021-03-25 06:34 UTC, behumb commented on training_service/backend/courses/models.py
> +
CourseProgress.objects.filter(is_complete=True).filter(completion_date__year=2021).count()

2021-03-29 12:10 UTC, denisorehovsky requested changes

2021-03-29 12:10 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +class UserViewSet(mixins.CreateModelMixin,
In your api any user can update any other user

2021-03-29 12:10 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +
Add unique together where it's necessary

2021-03-29 12:10 UTC, denisorehovsky commented on training_service/backend/courses/views.py
> +class CourseViewSet(viewsets.ModelViewSet):
Add permissions.
Also, what if the system has 1 million courses. When I try to get a list of courses, the api will try to generate a very big json file.

2021-03-29 12:10 UTC, denisorehovsky commented on training_service/backend/courses/serializers.py
> +class CourseSerializer(serializers.ModelSerializer):
It's enough for this pull request because it's too big, but this serializer is too small. It doesn't have all information that you need on the frontend. Should be fixed in the next PR.

2021-04-01 12:26 UTC, denisorehovsky requested changes

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/accounts/services/token_service.py
> +def get_user_token(user):
Why do you need this function if you're not using it?

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +def create(username, email, first_name, last_name, password, groups):
Rename this to `create_user`. It's easier to search

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +def update(user, username=None, first_name=None, last_name=None, email=None, groups=None):
Rename this to `update_user`. It's easier to search

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        user = request.user
This is not correct. You have such an endpoint:

```
PATCH /api/users/:id/
```

If request.user.id is, let's say, 10 and I'm sending a request to

```
PATCH /api/users/20/
``` 

And I get response 200, it doesn't make sense because I updated request.user (which is a user with id 10, not 20)

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +class Participation(models.Model):
What about uniqueness here?

2021-04-01 12:26 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +    completion_date = models.DateField('Completion date')
It's a required field? What if I just started a course? Why do I need to fill completion_date if I haven't completed it yet?

2021-04-02 08:36 UTC, denisorehovsky requested changes

2021-04-02 08:36 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    def update_user(self, request):
You should have this endpoint:
```
PATCH /api/users/:id/
```

Not this:
```
PATCH /api/users/update_user/
```

2021-04-02 08:36 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    @action(methods=['patch'], detail=False)
Did you test this?

2021-04-02 08:36 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    @action(methods=['patch'], detail=False)
I believe it will not work

2021-04-02 08:36 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +            models.UniqueConstraint(fields=['user', 'role'], name='participation_constraint')
I can add these rows into `participation` table:
```
user_id course_id role
1           1              STUDENT
1           1              TEACHER
```

How can I be a teacher and a student at the same time?

2021-04-02 09:17 UTC, denisorehovsky requested changes

2021-04-02 09:17 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    @action(methods=['patch'], detail=False)
It should be detail True

2021-04-02 09:17 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        if request.user != self.get_object():
Permissions should be in permission classes, not here

2021-04-02 09:17 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        user = self.get_object()
Any user can delete anyone?

2021-04-02 09:18 UTC, denisorehovsky requested changes

2021-04-02 09:18 UTC, denisorehovsky commented on training_service/backend/courses/models.py
> +            models.UniqueConstraint(fields=['id', 'user', 'role'], name='participation_constraint')
It will not solve the problem that I mentioned

2021-04-05 07:42 UTC, denisorehovsky requested changes
Why did you remove migration files?

2021-04-05 07:42 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        self.get_object()
What user are you trying to delete? Send me a screenshot of how you test this endpoint (insomnia or postman)

2021-04-05 07:42 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +    @action(methods=['patch'], detail=True)
For what user are you trying to reset password? Send me a screenshot of how you test this endpoint (insomnia or postman)

2021-04-05 07:42 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        self.get_object()
What user are you trying to update? Send me a screenshot of how you test this endpoint (insomnia or postman)

2021-04-05 07:44 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +        self.get_object()
user = self.get_object()

2021-04-05 07:50 UTC, denisorehovsky requested changes

2021-04-05 07:50 UTC, denisorehovsky commented on training_service/backend/accounts/permissions.py
> +class IsOwner(permissions.BasePermission):
Why is it called `IsOwner`. I would create something like that:
![image](https://user-images.githubusercontent.com/9641784/113550910-82948200-95fc-11eb-9ab3-ee575ee1d5c6.png)

Also, you can set different permissions in `get_permissions` method. Here's an example:
https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L67

2021-04-05 09:24 UTC, behumb commented on training_service/backend/accounts/views.py
> +        self.get_object()
![image](https://user-images.githubusercontent.com/37983577/113559327-d3f73e00-9609-11eb-8d22-51109861baae.png)

2021-04-05 09:27 UTC, behumb commented on training_service/backend/accounts/views.py
> +        self.get_object()
![image](https://user-images.githubusercontent.com/37983577/113559569-4ff18600-960a-11eb-8a56-b14761403bad.png)

2021-04-05 09:31 UTC, behumb commented on training_service/backend/accounts/views.py
> +    @action(methods=['patch'], detail=True)
![image](https://user-images.githubusercontent.com/37983577/113559958-e756d900-960a-11eb-9fa1-70a646d52f07.png)

2021-04-05 12:23 UTC, denisorehovsky requested changes

2021-04-05 12:23 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +    if group:
This piece of code can be removed. If you already created a student or a teacher, you should not be able to change its role

2021-04-05 12:23 UTC, denisorehovsky commented on training_service/backend/accounts/serializers.py
> +    group = serializers.CharField(max_length=50)
CharField? I can send anything here? You should have validation

2021-04-05 12:23 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +def create_user(username, email, first_name, last_name, password, group):
I would create `create_student` and `create_teacher` services instead.

2021-04-05 12:23 UTC, denisorehovsky commented on training_service/backend/accounts/services/user_service.py
> +    user_group = None
This code will break if `user_group` is not 'student' or 'teacher'

2021-04-05 12:23 UTC, denisorehovsky commented on training_service/backend/accounts/permissions.py
>          return request.user
What are you trying to do here? If you want to check whether a user is authenticated or not, you should do this instead:

```
request.user.is_authenticated
```

2021-04-06 06:14 UTC, denisorehovsky requested changes

2021-04-06 06:14 UTC, denisorehovsky commented on training_service/backend/accounts/permissions.py
> +        if view.action == 'teacher_create' or view.action == 'student_create':
Like I said earlier, you should override `get_permissions` method in view. I've sent you an example before.

2021-04-06 06:14 UTC, denisorehovsky commented on training_service/backend/accounts/views.py
> +            'group': Group.objects.get_or_create(name='Teacher')[0].id
I don't like this code to be honest. But ok, let's stick with that, and let's move on.

2021-04-06 06:52 UTC, denisorehovsky approved these changes

2021-04-06 07:10 UTC, merged